security:
  password_hashers:
    App\Entity\Utilisateur:
      algorithm: plaintext  # ⚠ à ne pas utiliser en production

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticators:
        - App\Security\UserAuthentificator
        - App\Security\GoogleAuthenticator
      logout:
        path: auth_oauth_logout
        target: auth_oauth_login
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 1 semaine
        path: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/profile/complete, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
