parameters:
  uploads_directory: "%kernel.project_dir%/public/uploads/images"
  kernel.secret: "%env(APP_SECRET)%"
  STRIPE_PUBLIC_KEY: '%env(STRIPE_PUBLIC_KEY)%'
  STRIPE_SECRET_KEY: '%env(STRIPE_SECRET_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Configuration spécifique du formulaire
  App\Form\LivresType:
    arguments:
      $slugger: "@slugger"
      $em: "@doctrine.orm.entity_manager"
    tags:
      - { name: form.type }

  # Configuration principale
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Service/'  # Exclure le dossier service pour le configurer séparément

  # Configuration spécifique pour le namespace service (avec 's' minuscule)
  App\Service\:
    resource: '../src/Service/'
    autowire: true
    autoconfigure: true