# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
  uploads_directory: "%kernel.project_dir%/public/uploads/images"
  STRIPE_PUBLIC_KEY: "%env(STRIPE_PUBLIC_KEY)%"
  STRIPE_SECRET_KEY: "%env(STRIPE_SECRET_KEY)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Configuration du formulaire LivresType
  App\Form\LivresType:
    arguments:
      $slugger: "@slugger"
      $em: "@doctrine.orm.entity_manager" # Injection de l'EntityManager
    tags:
      - { name: form.type }
  App\Controller\BotmanController:
    tags: ["controller.service_arguments"]
    public: true

  # makes classes in src/ available to be used as services
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
